force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <description>This table stores the correct answer for each question, with foreign keys referencing the corresponding question and answer option, and a boolean field indicating whether the answer is correct or not.</description>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/AnswerOption__c.field-meta.xml
<CustomField>
    <fullName>AnswerOption__c</fullName>
    <label>AnswerOption</label>
    <referenceTo>AnswerOption__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/AnswerText__c.field-meta.xml
<CustomField>
    <fullName>AnswerText__c</fullName>
    <label>Answer Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AnswerOption__c/AnswerOption__c.object-meta.xml
<CustomObject>
    <description>This table stores the possible answer options for each question, with a text field for each option and a foreign key referencing the corresponding question.</description>
    <label>AnswerOption</label>
    <nameField>
        <displayFormat>QO-{000000}</displayFormat>
        <label>AnswerOption Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AnswerOptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnswerOption__c/fields/AnswerOptionText__c.field-meta.xml
<CustomField>
    <fullName>AnswerOptionText__c</fullName>
    <label>AnswerOptionText</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AnswerOption__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>AnswerOptions</relationshipLabel>
    <relationshipName>AnswerOptions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>This table stores the questions for each quiz, including the text of the question, the ID of the quiz it belongs to, the ID of the question type, and optional fields for time limit and randomization.</description>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/QuestionText__c.field-meta.xml
<CustomField>
    <fullName>QuestionText__c</fullName>
    <label>QuestionText</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/QuestionType__c.field-meta.xml
<CustomField>
    <fullName>QuestionType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>QuestionType</label>
    <referenceTo>QuestionType__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/RandomizeOrder__c.field-meta.xml
<CustomField>
    <fullName>RandomizeOrder__c</fullName>
    <label>RandomizeOrder</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/TimeLimit__c.field-meta.xml
<CustomField>
    <fullName>TimeLimit__c</fullName>
    <defaultValue>30</defaultValue>
    <description>Time limit in seconds.</description>
    <label>TimeLimit</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuestionType__c/QuestionType__c.object-meta.xml
<CustomObject>
    <description>This table stores a list of possible question types, such as multiple choice, true/false, and short answer.</description>
    <label>QuestionType</label>
    <nameField>
        <displayFormat>QT-{000000}</displayFormat>
        <label>QuestionType Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuestionTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuestionType__c/fields/QuestionType__c.field-meta.xml
<CustomField>
    <fullName>QuestionType__c</fullName>
    <label>QuestionType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>multiple choice</fullName>
            </value>
            <value>
                <fullName>true/false</fullName>
            </value>
            <value>
                <fullName>short answer</fullName>
            </value>
            <value>
                <fullName>Curseur</fullName>
            </value>
            <value>
                <fullName>Puzzle</fullName>
            </value>
            <value>
                <fullName>Sondage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quiz__c/Quiz__c.object-meta.xml
<CustomObject>
    <description>This table stores information about each quiz, including its unique identifier, name, description, and the ID of the user who created it.</description>
    <label>Quiz</label>
    <nameField>
        <label>Quize Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quizes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <defaultValue>&apos;Please note that failing to select an answer within the allotted time will result in a loss of points&apos;</defaultValue>
    <description>This quiz consists of a series of questions designed to test your knowledge on [subject matter]. To begin, click the &quot;Start Quiz&quot; button below. You will have a limited amount of time to complete the quiz, so it is important to read each question carefully and answer to the best of your ability. You can only submit your answers once, so be sure to review your responses before submitting. Good luck!</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Quize Duration in seconds.</description>
    <label>Duration</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QuizController.cls
public without sharing class QuizController {
    
    @AuraEnabled(cacheable=true)
    public static QuizWrapper getQuizzesWithQuestionsAndOptions(Id quizId) {
        Quiz__c quiz = [SELECT Id, Name, Description__c, Duration__c
                        FROM Quiz__c WHERE Id = :quizId LIMIT 1];

        List<Question__c> questions = [SELECT Id, QuestionText__c, QuestionType__c, TimeLimit__c, 
                                       (SELECT Id, AnswerOptionText__c FROM AnswerOptions__r)
                                       FROM Question__c WHERE Quiz__c = :quiz.Id ORDER BY RandomizeOrder__c];

        List<QuestionWrapper> questionWrappers = new List<QuestionWrapper>();
        for (Question__c question : questions) {
            List<AnswerOption__c> answerOptions = question.AnswerOptions__r;
            List<Answer__c> correctAnswers = [SELECT Id, AnswerOption__c, AnswerText__c FROM Answer__c WHERE Question__c = :question.Id];
            questionWrappers.add(new QuestionWrapper(question, answerOptions, correctAnswers));
        }

        return new QuizWrapper(quiz, questionWrappers);
    }

    public class QuizWrapper {
        @AuraEnabled public Quiz__c quiz;
        @AuraEnabled public List<QuestionWrapper> questions;

        public QuizWrapper(Quiz__c quiz, List<QuestionWrapper> questions) {
            this.quiz = quiz;
            this.questions = questions;
        }
    }

    public class QuestionWrapper {
        @AuraEnabled public Question__c question;
        @AuraEnabled public List<AnswerOption__c> answerOptions;
        @AuraEnabled public List<Answer__c> correctAnswers;

        public QuestionWrapper(Question__c question, List<AnswerOption__c> answerOptions, List<Answer__c> correctAnswers) {
            this.question = question;
            this.answerOptions = answerOptions;
            this.correctAnswers = correctAnswers;
        }
    }
}